### PR TITLE
Merge development branch to master

### PR DESCRIPTION
**Pull request by tyalt1**
merge stable pre-alpha code

### CODE REVIEW

**Comment by ClaytonSmith** [comment]
LGTM

**Comment by mattwollf** [comment]
https://www.youtube.com/watch?v=SGbI-14neOs

**Comment by yuetlong** [comment]
can somebody walk me through how to test this?

**Comment by tyalt1** [comment]
1. Deploy on the RPi by running `python nonocast/main.py`
2. Test the frontend by going to the RPi IP address from another computer on your local network.
3. Enter either a YouTube or Twitch link into the address bar. From there the link should appear on the RPi display.

**Comment by yuetlong** [comment]
Unfortunately, web server didn't run as expected.
I did step 1, then i ran "telnet localhost 80". connection was refused.

**Comment by yuetlong** [comment]
nonobae set the port to 8000 that's why ....

**Pull request merged**
